import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginButton from "./components/LoginButton";
import ReduxProvider from './redux/providers';
import { ToastContainer } from "react-toastify";
import CartCount from "./components/CartCount";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SnapBuy",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastContainer/>
        <ReduxProvider>
          <nav className="flex px-4 py-3 bg-gray-800 text-white sticky top-0 z-50">
              <Link href={"/"} className="flex-[1] font-extrabold text-[1.7rem] ml-2 font-sans">SnapBuy</Link>
              {/* <div className="flex-[1] font-extrabold text-[1.5rem] ml-2">LOGO</div> */}
            <div className="flex-[1] flex flex-row-reverse list-none">
              <LoginButton/>
              <Link className="px-4 my-auto" href={'/productCart'}><CartCount/></Link>
              <Link className="px-4 my-auto" href={'/shop'}>Shop</Link>
            </div>
          </nav>
          <div className="h-screen overflow-scroll">
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
